export const strings = {
    app_name: "Ai Tools for Business",
    join_wishlist: "Join Wishlist",
    become_beta_tester: "Become a Beta Tester",
    main_title: "AI Tools all you need",
    copyright: "Copyright",
    submit: "Submit",
    cancel: "Cancel",
    emailMessage: "We will send you an invitation in your inbox",
    message: "Change your life using your favorite AI Tools, wants to become a tester and buy me a cup of coffee.",
    andText: "And",
    becomePatreon: "Buy me a Cup of Coffee",
    patreonWebsiteLink: "https://www.patreon.com/FavoriteAITools",
    favoriteAIToolsName: "Favorite AI Tools",
}